#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

def gradingStudents(grades):
   
# Declare an array where you will store the newly rounded values
    rounded = []
# Scan the array for values greater than or equal to 38
    for grade in grades:
        if grade >= 38:
# Get the modules and store it in a variable called res
            res = grade % 5
# If the modulus is greater or equal to 3, add the grade to the difference between 5 and modulus
# The difference between 5 and modulus is how much it will take to get to the next multiple of 5
            if res >= 3:
                grade += (5 - res)
# Append the result in the new array, rouneded
                rounded.append(grade)
# If conditions aren't met, append the value the way it is
            elif res<3:
                rounded.append(grade)
        else:
            rounded.append(grade)
            
    return rounded            


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
