#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    max_sum = min_sum = 0
#Get the sum of all the values in the array then minus the minimum value
    max_sum = sum(arr) - min(arr)

#Get the sum of all the values in the array then minus the maximum value    
    min_sum = sum(arr) - max(arr)

    print(min_sum, max_sum)
if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
